_common: !include "../shared.yaml"

name: graph-server
<<: *common

dependencies:
  - base

library:
  source-dirs:
    - src
  dependencies:
    - wai
    - stm
    - mtl
    - transformers
    - base
    - servant-server
  <<: *library

executables:
  exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - warp
      - graph-server
    <<: *executable

tests:
  test:
    main: Test.hs
    source-dirs: test
    dependencies:
      - graph-server
    <<: *test
